-- Canoas Sales OS: expansão aditiva de pipeline, catálogos, agenda, dicas e gamificação.
-- Todos os objetos permanecem no escopo do usuário autenticado e usam RLS.

alter type public.lead_stage add value if not exists 'meeting_no_show' after 'meeting_scheduled';
alter type public.lead_stage add value if not exists 'follow_up_2' after 'follow_up';
alter type public.lead_stage add value if not exists 'follow_up_3' after 'follow_up_2';
alter type public.lead_stage add value if not exists 'follow_up_4' after 'follow_up_3';
alter type public.lead_stage add value if not exists 'follow_up_5' after 'follow_up_4';
alter type public.lead_stage add value if not exists 'follow_up_6' after 'follow_up_5';

alter table public.leads
  add column if not exists archived_at timestamptz,
  add column if not exists archive_reason text;

alter table public.tasks
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists rescheduled_from timestamptz;

alter table public.activities
  add column if not exists event_type text,
  add column if not exists event_key text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

update public.activities
set event_type = case
  when type = 'task_completed' then 'task.completed'
  when type = 'stage_change' then 'lead.stage_changed'
  when type = 'note' then 'lead.note_added'
  else 'activity.' || type::text
end
where event_type is null;

update public.tasks set updated_at = created_at where updated_at is null;

create table if not exists public.catalog_options (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('niche', 'service_interest', 'source', 'action_type')),
  label text not null check (char_length(trim(label)) between 1 and 120),
  normalized_value text generated always as (lower(regexp_replace(trim(label), '\s+', ' ', 'g'))) stored,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists catalog_options_user_category_value_uidx
  on public.catalog_options (user_id, category, normalized_value);
create index if not exists catalog_options_user_category_active_idx
  on public.catalog_options (user_id, category, active, label);

alter table public.tasks
  add column if not exists action_type_id uuid references public.catalog_options(id) on delete set null;

create table if not exists public.daily_tips (
  id bigint generated by default as identity primary key,
  position integer not null unique,
  category text not null,
  content text not null check (char_length(content) between 30 and 500),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_daily_tips (
  user_id uuid not null references auth.users(id) on delete cascade,
  local_date date not null,
  tip_id bigint not null references public.daily_tips(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  read_at timestamptz,
  primary key (user_id, local_date),
  unique (user_id, tip_id)
);

alter table public.catalog_options enable row level security;
alter table public.daily_tips enable row level security;
alter table public.user_daily_tips enable row level security;

revoke all on table public.catalog_options from anon, authenticated;
revoke all on table public.daily_tips from anon, authenticated;
revoke all on table public.user_daily_tips from anon, authenticated;
grant select, insert, update, delete on table public.catalog_options to authenticated;
grant select on table public.daily_tips to authenticated;
grant select, insert, update on table public.user_daily_tips to authenticated;

drop policy if exists catalog_options_select_own on public.catalog_options;
create policy catalog_options_select_own on public.catalog_options for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists catalog_options_insert_own on public.catalog_options;
create policy catalog_options_insert_own on public.catalog_options for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists catalog_options_update_own on public.catalog_options;
create policy catalog_options_update_own on public.catalog_options for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
drop policy if exists catalog_options_delete_own on public.catalog_options;
create policy catalog_options_delete_own on public.catalog_options for delete to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists daily_tips_select_authenticated on public.daily_tips;
create policy daily_tips_select_authenticated on public.daily_tips for select to authenticated
  using (active = true);

drop policy if exists user_daily_tips_select_own on public.user_daily_tips;
create policy user_daily_tips_select_own on public.user_daily_tips for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists user_daily_tips_insert_own on public.user_daily_tips;
create policy user_daily_tips_insert_own on public.user_daily_tips for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists user_daily_tips_update_own on public.user_daily_tips;
create policy user_daily_tips_update_own on public.user_daily_tips for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create index if not exists leads_user_archived_stage_idx
  on public.leads (user_id, archived_at, stage, updated_at desc);
create index if not exists tasks_lead_id_idx on public.tasks (lead_id);
create index if not exists tasks_user_open_due_idx on public.tasks (user_id, completed_at, due_at);
create index if not exists activities_user_id_idx on public.activities (user_id);
create index if not exists activities_lead_created_idx on public.activities (lead_id, created_at desc);
create unique index if not exists activities_user_event_key_uidx
  on public.activities (user_id, event_key) where event_key is not null;
create index if not exists user_daily_tips_user_tip_idx on public.user_daily_tips (user_id, tip_id);

with base(category, tip) as (
  values
    ('prospecção', 'Pesquise um detalhe concreto do negócio antes de iniciar a conversa; personalização específica aumenta a chance de resposta.'),
    ('prospecção', 'Abra a mensagem com o motivo do contato e o benefício mais provável para aquele lead em até duas frases.'),
    ('prospecção', 'Evite começar falando sobre sua empresa; comece mostrando que você entendeu uma situação do potencial cliente.'),
    ('prospecção', 'Separe dez minutos para revisar os contatos sem próxima ação e devolvê-los a uma data realista.'),
    ('prospecção', 'Use uma pergunta simples no primeiro contato para facilitar uma resposta curta e iniciar a conversa.'),
    ('qualificação', 'Confirme problema, impacto, urgência e poder de decisão antes de considerar uma oportunidade qualificada.'),
    ('qualificação', 'Pergunte como o cliente resolve o problema hoje e o que acontece quando nada é feito.'),
    ('qualificação', 'Registre as palavras exatas usadas pelo lead para descrever a dor; elas ajudam na proposta e no follow-up.'),
    ('qualificação', 'Descubra quem participa da decisão e combine como essa pessoa será envolvida no processo.'),
    ('qualificação', 'Transforme respostas vagas em números: frequência, tempo perdido, receita afetada ou custo atual.'),
    ('reunião', 'Envie confirmação com horário, duração, objetivo e link da reunião para reduzir faltas.'),
    ('reunião', 'Antes da reunião, defina as três perguntas que precisam ser respondidas para decidir o próximo passo.'),
    ('reunião', 'Termine a reunião com um próximo passo, responsável e data definidos em voz alta.'),
    ('reunião', 'Após um no-show, trate o imprevisto com respeito e ofereça duas opções objetivas de novo horário.'),
    ('reunião', 'Reserve os últimos cinco minutos da reunião para confirmar entendimento e próximos compromissos.'),
    ('proposta', 'Conecte cada parte da proposta a um problema mencionado pelo cliente durante a descoberta.'),
    ('proposta', 'Apresente valor e resultado esperado antes de mostrar o preço.'),
    ('proposta', 'Evite enviar proposta sem combinar uma conversa de revisão já marcada.'),
    ('proposta', 'Inclua escopo, prazo, responsabilidades e critérios de sucesso de forma inequívoca.'),
    ('proposta', 'Quando houver mais de uma opção, explique para qual cenário cada alternativa foi desenhada.'),
    ('follow-up', 'Faça follow-up acrescentando informação útil, contexto ou uma pergunta nova; não envie apenas lembretes.'),
    ('follow-up', 'Use intervalos definidos para follow-up e pare de depender da memória.'),
    ('follow-up', 'Mencione o próximo passo combinado anteriormente para tornar a mensagem contextual.'),
    ('follow-up', 'Se não houver resposta, varie o canal e mantenha a mesma mensagem central.'),
    ('follow-up', 'Após várias tentativas, encerre o ciclo com elegância e deixe uma porta clara para retomada.'),
    ('objeções', 'Antes de responder a uma objeção, confirme se ela é a única barreira para avançar.'),
    ('objeções', 'Pergunte o que o cliente está comparando quando disser que o preço está alto.'),
    ('objeções', 'Valide a preocupação do lead e depois responda com evidência, exemplo ou alternativa concreta.'),
    ('objeções', 'Não conceda desconto sem receber uma contrapartida de prazo, escopo ou condição de pagamento.'),
    ('objeções', 'Registre objeções recorrentes para melhorar mensagens, qualificação e proposta.'),
    ('negociação', 'Defina antecipadamente seu limite de negociação e quais itens podem ser trocados.'),
    ('negociação', 'Recapitule os pontos já acordados antes de tratar o último impasse.'),
    ('negociação', 'Quando a decisão atrasar, pergunte qual etapa interna ainda falta e quem é responsável por ela.'),
    ('fechamento', 'Peça a decisão de forma direta quando problema, valor e condições já estiverem claros.'),
    ('fechamento', 'Depois do aceite, confirme imediatamente contrato, pagamento, início e responsável pela implantação.'),
    ('gestão', 'Priorize ações atrasadas antes de abrir novas frentes; pendências antigas degradam o pipeline.'),
    ('gestão', 'Mantenha uma única próxima ação aberta por lead para deixar a prioridade inequívoca.'),
    ('gestão', 'Revise diariamente oportunidades quentes sem próxima ação futura.'),
    ('gestão', 'Use o estágio para refletir fatos já ocorridos, e não expectativas do vendedor.'),
    ('gestão', 'Arquive oportunidades fora de foco sem apagar o histórico necessário para uma retomada.'),
    ('produtividade', 'Agrupe ligações em um bloco curto para reduzir troca de contexto.'),
    ('produtividade', 'Comece o dia pela ação comercial de maior impacto, antes de tarefas administrativas.'),
    ('produtividade', 'Conclua cada contato registrando resultado e próxima ação no mesmo momento.'),
    ('produtividade', 'Proteja blocos de prospecção na agenda como compromissos com o próprio negócio.'),
    ('produtividade', 'Use modelos de mensagem como ponto de partida e personalize o trecho que prova relevância.'),
    ('relacionamento', 'Envie um resumo curto após conversas importantes para confirmar alinhamento.'),
    ('relacionamento', 'Celebre avanços do cliente e mantenha contato mesmo quando a venda não é imediata.'),
    ('relacionamento', 'Peça indicação somente depois de entregar valor ou receber um sinal claro de satisfação.'),
    ('relacionamento', 'Em reativações, mencione o contexto anterior e a mudança que justifica o novo contato.'),
    ('mensagem', 'Leia a mensagem em voz alta e corte palavras que não ajudam o cliente a decidir ou responder.'),
    ('mensagem', 'Prefira frases curtas, um pedido por mensagem e linguagem que o cliente usaria.'),
    ('mensagem', 'Troque afirmações genéricas por uma evidência, resultado ou observação verificável.'),
    ('mensagem', 'Adapte o nível de formalidade ao canal e à forma como o lead se comunica.'),
    ('mensagem', 'Finalize com uma chamada para ação específica, fácil de responder e adequada ao momento.'),
    ('métricas', 'Acompanhe conversão entre etapas para descobrir onde o processo perde mais oportunidades.'),
    ('métricas', 'Meça atividades válidas concluídas, sem premiar cliques ou registros sem resultado.'),
    ('métricas', 'Compare a idade das oportunidades por estágio para identificar negociações paradas.'),
    ('métricas', 'Avalie a taxa de resposta por origem para concentrar esforço nos canais com melhor retorno.'),
    ('métricas', 'Revise semanalmente ganhos e perdas para ajustar abordagem com base em evidências.'),
    ('confiança', 'Se não souber uma resposta, combine quando irá retornar e cumpra o horário prometido.'),
    ('confiança', 'Evite urgência artificial; use prazos reais e explique por que eles existem.'),
    ('confiança', 'Confirme entendimento antes de recomendar uma solução.'),
    ('confiança', 'Se a solução não servir ao lead, diga isso com clareza e preserve a relação.'),
    ('confiança', 'Mantenha registros objetivos para que qualquer retomada respeite o histórico da conversa.'),
    ('processo', 'Defina critérios observáveis para avançar ou recuar cada estágio do pipeline.'),
    ('processo', 'Não deixe leads ganhos ou perdidos misturados às oportunidades que ainda exigem ação.'),
    ('processo', 'Use nutrição futura somente quando houver uma razão e uma janela de retomada plausíveis.'),
    ('processo', 'Quando uma tarefa for reagendada, registre o motivo para identificar padrões de adiamento.'),
    ('processo', 'Revise campos incompletos nos leads mais valiosos antes da próxima conversa.'),
    ('foco', 'Escolha três missões comerciais possíveis para o dia e acompanhe o progresso até concluí-las.'),
    ('foco', 'Uma próxima ação precisa começar com um verbo e indicar um resultado observável.'),
    ('foco', 'Dê prioridade a leads com urgência, aderência e acesso ao decisor.'),
    ('foco', 'Reduza o número de oportunidades ativas quando não houver capacidade real de acompanhá-las.')
), contexts(context) as (
  values
    ('Aplique hoje no primeiro bloco comercial.'),
    ('Teste em uma oportunidade quente e registre o resultado.'),
    ('Use na próxima conversa e ajuste com base na resposta.'),
    ('Transforme isso em um hábito antes de encerrar o dia.'),
    ('Escolha um lead parado e coloque a prática em ação agora.')
), numbered as (
  select row_number() over (order by base.category, base.tip, contexts.context)::integer as position,
         base.category,
         base.tip || ' ' || contexts.context as content
  from base cross join contexts
)
insert into public.daily_tips (position, category, content)
select position, category, content from numbered where position <= 365
on conflict (position) do nothing;
